//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFPageSwitch
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars
    {
        public long id { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public int year { get; set; }
        public int price { get; set; }
        public double margin { get; set; }
        public double displ { get; set; }
        public int mileage { get; set; }
        public string desc { get; set; }
        public string fuelType { get; set; }
        public string photo { get; set; }
        public int power { get; set; }
        public string trany { get; set; }
        public Nullable<long> parking { get; set; }
    }
}
