//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFPageSwitch
{
    using System;
    using System.Collections.Generic;
    
    public partial class import
    {
        public long id { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public long year { get; set; }
        public double displ { get; set; }
        public string fuelType { get; set; }
        public string trany { get; set; }
        public string VClass { get; set; }
    }
}
