//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFPageSwitch
{
    using System;
    using System.Collections.Generic;
    
    public partial class transactions
    {
        public long id { get; set; }
        public string datetime { get; set; }
        public string car { get; set; }
        public long price { get; set; }
        public long balance { get; set; }
        public string buyer_name { get; set; }
        public string buyer_surname { get; set; }
        public string buyer_idnbr { get; set; }
        public string buyer_address { get; set; }
        public string buyer_postalcode { get; set; }
        public string buyer_city { get; set; }
        public string tr_type { get; set; }
        public string filename { get; set; }
    }
}
